project:
  type: website

website:
  title: "<img src='/images/climate_icon.png' alt='Climate' style='width: 1.75em; height: 1.75em; border-radius: 50%'> <b>Weather Gurus  </b>" 
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO523-S24/project-01-Weather-Gurus
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: default
    toc: true

execute:
  freeze: auto
