---
title: "Global Temperature Analysis"
subtitle: "Proposal"
format: html
editor: visual
jupyter: python3
---

```{python}
#| label: load-pkgs
#| message: false
#| echo: false
import numpy as np
import pandas as pd
from tabulate import tabulate
```




## Introduction

The dataset is provided by NASA by combining land-surface, sea surface, and air temperature anomalies. The values in the dataset are deviations from the corresponding 1951-1980 means, indicating how much warmer or colder it is than normal for a particular place and time, and the normal means the average over the 30 years 1951-1980 for that place and time of year. More precisely, the base 1951-1980 mean is subtracted from the absolute temperature to get the anomaly.

---

::: {style="text-align: justify;"}
## Dataset

The dataset is provided by NASA by combining land-surface, sea surface, and air temperature anomalies. The values in the dataset are deviations from the corresponding 1951-1980 means, indicating how much warmer or colder it is than normal for a particular place and time, and the normal means the average over the 30 years 1951-1980 for that place and time of year. More precisely, the base 1951-1980 mean is subtracted from the absolute temperature to get the anomaly.
The dataset contains four CSV files, providing temperature anomalies across different spatial and temporal scales for a long period from 1880 to 2022. 
 
 Analyzing these datasets can help us understand the past and present climate trends and potentially predict future patterns.The datasets provide a comprehensive view of temperature changes from different perspectives - global, Northern Hemisphere, Southern Hemisphere, and zonal annual temperatures. Moreover, one of the team members is very familiar with spatial-temporal datasets as he is doing a Ph.D. in hydrology and atmospheric sciences; hence, having good domain knowledge can help us ask reasonable questions and do the analysis faster.
:::

----
## Questions

1. How have zonal annual temperatures changed over the years? Can we detect any latitudinal pattern? When was the hottest year on record?

2. How have the hemispheric seasonal (monthly) temperatures changed over the years? Can we detect any upward or downward trend in any seasons (months) and any of the hemispheres? Which seasons (months) show more erratic behavior?

---

## Analysis plan


#### Question one

##### Variables Involved

- **Yearly Temperature Anomalies**: Utilizing the `J-D` (January-December average) column from `global_temps.csv`, `nh_temps.csv`, and `sh_temps.csv` datasets to assess annual temperature anomalies globally and across hemispheres.

- **Seasonal Temperature Anomalies**: Focusing on `DJF` (December-January-February) and `JJA` (June-July-August) anomalies for the cool and warm seasons, respectively, in the Northern Hemisphere, with inverted seasons for the Southern Hemisphere.

##### Variables to be Created

- **2023 Temperature Anomalies**: Adding complete data for 2023 from the GISS Surface Temperature Analysis (GISTEMP v4) to the TidyTuesday datasets.

- **Seasonal Anomalies for 2023**: Calculating mean temperature anomalies for the cool (November-April) and warm (May-October) seasons for 2023.

##### External Data

- **2023 Temperature Data**: Sourcing the missing 2023 temperature anomaly data from NASA's GISS Surface Temperature Analysis ([NASA Goddard Institute for Space Studies](https://data.giss.nasa.gov/gistemp/)).

##### Statistical Methods

- **Time Series Analysis**: To compare 2023 temperature anomalies against historical records.

- **Trend Analysis**: Employing linear regression to assess temperature anomaly trends over the years, including 2023.

- **Comparative Analysis**: Comparing 2023 average temperature anomalies against historical maxima for global and hemispheric analyses, and evaluating cool and warm season anomalies.

----

2.  We should use variables inside the zonnan_temps.csv dataset. Initially, we should transform the data from a wide format to a long format by defining a new column called zones and merging all eight variables related to zones (i.e. 24N-44N, …) to that column. As we are focusing on annual zonal anomalies in this qustion, we can skip Glob, NHem, and SHem variables. Finally, we would have a dataframe with three columns with one represnting year, one represnting zone and the last contains the annomalies.
We can create time series for each zone to visualize the pattern of zonal annual temperature anomalies, emphasizing any noticeable trends or deviation from zonal long-term mean anomaly. Also, we can employ heatmaps to map the variance of the zonal annual temperature anomaly on top of countries and oceans boundaries to show which hemisphere behaves more erratically.


3. We should use nh_temps.csv and sh_temps.csv datasets. We should start by converting the dataset of each hemispheres to a long format by defining one new column for month (season) and one column that shows the hemispheres (NH and SH). Finally, we can merge the dataframes vertically to arrive at a one comprehensive dataframe. 
We can compare the pattern of seasonal temperature anomalies over the Northern and Southern hemispheres separately and collectively. We can use time series, box plots, or histograms to illustrate and compare the time series and statistical distribution of seasonal temperature anomalies in the northern and southern hemispheres to discuss how different and similar they are. It may be interesting to create a similar visualization to the previous question with deviation from long-term anomalies. This would not only capture how seasonal temperatures have strayed from some long-term average, but how temperatures are fluctuating relative to even temporally local averages


